library("FactoMineR", lib.loc="~/R/win-library/3.1")
library("ggplot2", lib.loc="~/R/win-library/3.1")
greppo <- read.csv("D:/Travail/Tableaux/Statistiques/R/bulliot_analyse.csv", sep=";")
summary(greppo)
res.mca = MCA(greppo, quali.sup=c(20:23), graph=FALSE)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("var","quali.sup"), cex=0.7)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","var"), cex=0.7)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("var","quali.sup"), cex=0.7, axes=3:4)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7, axes=3:4)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","var"), cex=0.7, axes=3:4)
plot.MCA(res.mca, autoLab=c("yes"),selectMod = "cos2 10")
plot.MCA(res.mca, autoLab=c("yes"),selectMod = "contrib 10")
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7, selectMod = "cos2 10")
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7, selectMod = "contrib 10")
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7, selectMod = "cos2 10", axes=3:4)
plot.MCA(res.mca, autoLab=c("yes"), invisible=c("ind","quali.sup"), cex=0.7, selectMod = "contrib 10", axes=3:4)
summary(res.mca)
res.hcpc <- HCPC(res.mca, nb.clust=0, conso=0, min=3, max=10)
dimdesc(res.mca)
dimdesc(res.mca,axes=1:2, proba=0.05)
dimdesc(res.mca,axes=3:4, proba=0.05)
x11()
plotellipses(res.mca)
res.mca$eig
aa=as.factor(rep(1:10,each=100))
bb=cbind.data.frame(aa,aa,aa,aa,aa,aa,aa,aa,aa,aa)
colnames(bb)=paste("a",1:10,sep="")
res=MCA(bb,graph=FALSE)
res$eig[1:10,]
burt=t(tab.disjonctif(greppo[,1:19]))%*%tab.disjonctif(greppo[,1:23])
res.burt=CA(burt, graph=FALSE)
res.burt$eig[1:10,]
res.mca$ind$contrib
res.mca$ind$cos2
res.mca$var$contrib
res.mca$var$cos2
library(cluster)
classif = agnes(res.mca$ind$coord,method="ward")
x11()
plot(classif,main="Dendrogram",ask=F,which.plots=2,labels=F)
clust = cutree(classif,k=3)
greppo.comp = cbind.data.frame(greppo,res.mca$ind$coord[,1:3],factor(clust))
res.aux = MCA(greppo.comp, quali.sup=c(20:23,24,25,26,27), graph=F)
x11()
plot(res.aux,invisible=c("quali.sup","var","quanti.sup"),habillage=27)
catdes(greppo.comp,ncol(greppo.comp))